replicaCount: 1
image:
  repository: my-org/inference-router
  tag: dev
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  KAFKA_BROKERS: "kafka.default.svc.cluster.local:9092"
  INPUT_TOPIC: "features"
  TRITON_URL: "triton.dev.svc.cluster.local:8001"
