apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: voice-detect
  namespace: argocd
spec:
  description: AI Voice Detector project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
